apiVersion: v1
stringData:
    CF_API_EMAIL: ENC[AES256_GCM,data:vQTKguuDVxfiCekBZFT+R3xwbQYo,iv:mDts0BXFe8tQxkHuphohkecC7MPH7RRwTjPk4DOC/YE=,tag:VMm7d9cwksB++tmvT8mP+Q==,type:str]
    EXTERNAL_DNS_DOMAIN_FILTER: ENC[AES256_GCM,data:EvCB6GTTqAFiC+Bw8I9x/A==,iv:HM/YwFBJPcinUQUyOxGOlRHDbrepzYyI8Kzh1rWJEvE=,tag:9rjFIbp5kLxyb9Lx4fY5kA==,type:str]
    EXTERNAL_DNS_ZONE_ID_FILTER: ENC[AES256_GCM,data:CMXtg9THeWqlLHr93T0kfJgR6KrL0WAK2Sn0i0Hegss=,iv:YiJJY6NPRjqHlgyxbzyn+lpV8AUXAwWT5cJyGD5xkM0=,tag:xB0y5B74feyDMCRRBFzEww==,type:str]
metadata:
    name: external-dns-secret-config
    namespace: external-dns
sops:
    age:
        - recipient: age1eglsl9yplq9t3pemaxhpsvd956h2j8n67llvm55hrvc3zsr67utqfs25um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUnFGcHNQR1FEL1Q2Q1lo
            a2RncVZXWWJWbGxGcVpPNW14RHpZUjg3T0NVCkMrVmVyTXZtMjlGS2ZLNjNxeUNP
            ZXdNSUlBZE9NTFlaNjkvYzZ0anZvNHcKLS0tIElkMndPNVdRYzBaTGpMTVJhbUor
            RFhlZktTOC9uY20vcFRHVTZNU0YycncK6zVrQbbRjf5eIAYo4frsyULQdmrNSBJ4
            58KW0pAXpgPZ/fkIvcgqgIE41z5Yz085m5bKnwm5Tpvd3cIIZcaC+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T17:58:08Z"
    mac: ENC[AES256_GCM,data:zZs4YIXLXFN/7X5wpWc91d5rOyCbUOjYcWo99QTDmbSxQjbC691b0pL6Ooy8MWdDhCtpdg1BAgni4fdwV4BlHXOPJK5k/6+hp7sHmd6HIUeJouS0zkItprFsJP7RHJtGIhc4ICpoXwFiPUghqsFclOtrnkWKgIeoL9dgcRKtLNs=,iv:x9EWy5Zs3Ff4jbmgIs8vAtyuj1sZCXuSXSQ/lyT1h4c=,tag:jSNH8Q83w77ca9LM0HPSrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
