apiVersion: v1
data:
    CF_API_EMAIL: ENC[AES256_GCM,data:uJiogI82z/B3J/1114i43hUHVbu3,iv:xD8ceEFMepYO0fam6tJbqkQIU9Drs7QibFLSvRNDMkk=,tag:QhI9ypshmgQUk36T4vwxfA==,type:str]
    EXTERNAL_DNS_DOMAIN_FILTER: ENC[AES256_GCM,data:bf7Rdh6A8vTzkSR3qkN12Q==,iv:hmWawx3G6iTfn57OZ921heuV0jggmxWKfemgFAmh/cY=,tag:G5+KNY6fud5RFlBr8Cs2KA==,type:str]
    EXTERNAL_DNS_ZONE_ID_FILTER: ENC[AES256_GCM,data:ocZQtowjdSvBykYFpgC0X44aIlwShLKQMXLND0FEtiw=,iv:v8jVAU96aN5jseFYtY9gVU8I9ihueVAmbwn0iLSe+bc=,tag:REZpuNa3stO5X1BMfvqRdw==,type:str]
metadata:
    name: external-dns-secret-config
    namespace: external-dns
sops:
    age:
        - recipient: age1eglsl9yplq9t3pemaxhpsvd956h2j8n67llvm55hrvc3zsr67utqfs25um
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBS1RadWQ0K09sV3dUVUNB
            czBIRE9SOXVLRWExV0tLNFBFczFZUTV2cGo0CkFHY3hyVWNxcnVMOEU4RXJkdE1s
            MThra2ZJNzl6RVFOekNXQU1sdTNWNDAKLS0tIFVxOFpHOVRKQlA5MERhUjB2QmQx
            TCs3aTUwcHVTLzV2dXhVRTNNeW91bTAKnt9Q1hcQZx7/Z+cx4rlY8SaVeoI47x4x
            Cx2Sg5BrIn6kud3+FdHcT+JKAOaZQ/JOAB+IkyIe1M4/vTA04hh94w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T10:23:57Z"
    mac: ENC[AES256_GCM,data:JSWAuOYcyyvkMh8wnJmqSb0iOgd7BaszJvNeIKKHtmqWEw9HzxJczH8WhubkANbIWKlf5PcrBVtlmfVtoH0ipT13RvYA345qCDeeabcQiLt7llw8B5CToBetkF2S4kgguLFCjydHW71AWS3VJySajYqB8K37gw+YPS6weSMH3uE=,iv:DizeeyB7UqswI3ljmFETmSIkZuZRV8lbynN2qZPAxN0=,tag:R+22SaNz3OpIZiZGTk7pOQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
