apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emissary-crds-chart
  namespace: cluster-config
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/emissary-ingress