apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emissary-crds-chart
  namespace: cluster-config
spec:
  interval: 10m
  timeout: 6m
  chart:
    spec:
      chart: emissary-crds-chart
      version: '3.10.0'
      sourceRef:
        kind: HelmRepository
        name: emissary-crds-chart
      interval: 5m
  releaseName: emissary-crds-chart
  targetNamespace: emissary-system
  storageNamespace: emissary-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true 
    remediation:
      retries: 3
  test:
    enable: false
  rollback:
    cleanupOnFail: true