apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: emissary-ingress
  namespace: cluster-config
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/emissary-ingress