apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: emissary-ingress
  namespace: cluster-config
spec:
  interval: 10m
  timeout: 10m
  chart:
    spec:
      chart: emissary-ingress
      version: '3.10.0'
      sourceRef:
        kind: HelmRepository
        name: emissary-ingress
      interval: 5m
  releaseName: emissary-ingress
  targetNamespace: emissary
  storageNamespace: emissary
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true 
    remediation:
      retries: 3
  test:
    enable: false
  rollback:
    cleanupOnFail: true
  values:
    scope:
      singleNamespace: emissary
    image:
      repository: ghcr.io/emissary-ingress/emissary
      tag: 3.10.0
    podLabels:
      ers-role: ingress-controller
    adminService:
      create: false
    replicaCount: 1
    createDefaultListeners: true
    module: 
      cluster_request_timeout_ms: 30000
      listener_idle_timeout_ms: 180000 
      use_remote_address: true
      suppress_envoy_headers: true
      diagnostics:
        enabled: false
    env:
      SCOUT_DISABLE: 1
    serviceAccount: 
      create: yes
      name: emissary-ingress