apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helmrelease.yaml
  - helmrepository.yaml
  # - host-main.yaml

patches:
 - target:
      kind: Role
      name: emissary-ingress
   patch: |-
    - op: add 
      path: /rules/-
      value:             
        apiGroups: ["discovery.k8s.io"]
        resources: ["endpointslices"]
        verbs: ["get","watch","list"]